/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktoptoko;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nahdya
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        barang = new javax.swing.JPanel();
        tbarang = new javax.swing.JLabel();
        transaksi = new javax.swing.JPanel();
        ttransaksi = new javax.swing.JLabel();
        supplier = new javax.swing.JPanel();
        tsupplier = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu utama");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 21, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barang.setBackground(new java.awt.Color(255, 204, 204));
        barang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barangMouseExited(evt);
            }
        });

        tbarang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tbarang.setText("Barang");

        javax.swing.GroupLayout barangLayout = new javax.swing.GroupLayout(barang);
        barang.setLayout(barangLayout);
        barangLayout.setHorizontalGroup(
            barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tbarang)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        barangLayout.setVerticalGroup(
            barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangLayout.createSequentialGroup()
                .addComponent(tbarang)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel2.add(barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        transaksi.setBackground(new java.awt.Color(255, 204, 204));
        transaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transaksiMouseExited(evt);
            }
        });

        ttransaksi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ttransaksi.setText("Transaksi");

        javax.swing.GroupLayout transaksiLayout = new javax.swing.GroupLayout(transaksi);
        transaksi.setLayout(transaksiLayout);
        transaksiLayout.setHorizontalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ttransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transaksiLayout.setVerticalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiLayout.createSequentialGroup()
                .addComponent(ttransaksi)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel2.add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 100, 30));

        supplier.setBackground(new java.awt.Color(255, 204, 204));
        supplier.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierMouseExited(evt);
            }
        });

        tsupplier.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tsupplier.setText("Supplier");

        javax.swing.GroupLayout supplierLayout = new javax.swing.GroupLayout(supplier);
        supplier.setLayout(supplierLayout);
        supplierLayout.setHorizontalGroup(
            supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tsupplier)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        supplierLayout.setVerticalGroup(
            supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierLayout.createSequentialGroup()
                .addComponent(tsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel2.add(supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 100, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 400, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangMouseEntered
tbarang.setForeground(Color.white);
barang.setBackground(new Color(255,153,102));
    }//GEN-LAST:event_barangMouseEntered

    private void transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseEntered
ttransaksi.setForeground(Color.white);
transaksi.setBackground(new Color(255,153,102));
    }//GEN-LAST:event_transaksiMouseEntered

    private void supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseEntered
tsupplier.setForeground(Color.white);
supplier.setBackground(new Color(255,153,102));
    }//GEN-LAST:event_supplierMouseEntered

    private void barangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangMouseExited
tbarang.setForeground(Color.black);
barang.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_barangMouseExited

    private void transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseExited
ttransaksi.setForeground(Color.black);
transaksi.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_transaksiMouseExited

    private void supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseExited
tsupplier.setForeground(Color.black);
supplier.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_supplierMouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
logout lu=new logout();
lu.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangMouseClicked
barang br=new barang();
br.setVisible(true);
this.dispose();
    }//GEN-LAST:event_barangMouseClicked

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
transaksi tr=new transaksi();
tr.setVisible(true);
this.dispose();
    }//GEN-LAST:event_transaksiMouseClicked

    private void supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseClicked
supplier sp=new supplier();
sp.setExtendedState(JFrame.NORMAL);
sp.setVisible(true);
this.dispose();
    }//GEN-LAST:event_supplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel supplier;
    private javax.swing.JLabel tbarang;
    private javax.swing.JPanel transaksi;
    private javax.swing.JLabel tsupplier;
    private javax.swing.JLabel ttransaksi;
    // End of variables declaration//GEN-END:variables
}
